import { Injectable } from '@nestjs/common';
import { DatabaseService } from '../database.service';

export interface RefreshTokenRecord {
  id: string;
  user_id: string;
  token_hash: string;
  expires_at: Date;
  created_at: Date;
  revoked_at: Date | null;
}

@Injectable()
export class RefreshTokensRepository {
  constructor(private readonly db: DatabaseService) {}

  /** id is generated by the caller so it can be embedded as the refresh JWT's `jti` before hashing. */
  async create(
    id: string,
    userId: string,
    tokenHash: string,
    expiresAt: Date,
  ): Promise<RefreshTokenRecord> {
    const result = await this.db.query<RefreshTokenRecord>(
      `INSERT INTO refresh_tokens (id, user_id, token_hash, expires_at)
       VALUES ($1, $2, $3, $4)
       RETURNING *`,
      [id, userId, tokenHash, expiresAt],
    );
    return result.rows[0];
  }

  async findActiveById(id: string): Promise<RefreshTokenRecord | null> {
    const result = await this.db.query<RefreshTokenRecord>(
      `SELECT * FROM refresh_tokens
       WHERE id = $1 AND revoked_at IS NULL AND expires_at > NOW()`,
      [id],
    );
    return result.rows[0] ?? null;
  }

  async revoke(id: string): Promise<void> {
    await this.db.query('UPDATE refresh_tokens SET revoked_at = NOW() WHERE id = $1', [id]);
  }

  async revokeAllForUser(userId: string): Promise<void> {
    await this.db.query(
      'UPDATE refresh_tokens SET revoked_at = NOW() WHERE user_id = $1 AND revoked_at IS NULL',
      [userId],
    );
  }

  /** Lazily prune expired/revoked rows for a user, called on login (SPEC.md 3.1). */
  async pruneStaleForUser(userId: string): Promise<void> {
    await this.db.query(
      'DELETE FROM refresh_tokens WHERE user_id = $1 AND (expires_at < NOW() OR revoked_at IS NOT NULL)',
      [userId],
    );
  }
}
